#ifndef __LED_H
#define __LED_H
#define LED0_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_5)
#define LED0_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET)
#define LED0_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET)
#define LED1_TOGGLE() HAL_GPIO_TogglePin(GPIOE, GPIO_PIN_5)
#define LED1_ON() HAL_GPIO_WritePin(GPIOE, GPIO_PIN_5, GPIO_PIN_RESET)
#define LED1_OFF() HAL_GPIO_WritePin(GPIOE, GPIO_PIN_5, GPIO_PIN_SET)
#endif
